name: Release Jive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
           ref: jive

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
           ref: gh-pages
           path: gh-pages

      - name: Set Version
        id: set-version
        run: |
          cat VERSION >> $GITHUB_OUTPUT

      - name: Set Filename Version
        id: set-filename
        run: |
          FNAME=${{ steps.set-version.outputs.version }}
          echo "fileversion=${FNAME//./_}" >>  $GITHUB_OUTPUT

      - name: Zip Repository
        id: zip
        working-directory: ./src
        run: |
          zip ../CustomClock -9r *.lua *.txt
          mv ../CustomClock.zip ../CustomClock${{ steps.set-filename.outputs.fileversion }}.zip
          cp ../CustomClock*.zip ../gh-pages/

      - name: Setup Perl
        run: |
          sudo apt-get install -y libxml-simple-perl libdigest-sha-perl

      - name: Update SHA and Version in repo.xml
        working-directory: ./gh-pages
        id: tag
        run: |
          url="http://urknall.github.io"
          perl ../release.pl repo.xml ${{ steps.set-version.outputs.version }} CustomClock${{ steps.set-filename.outputs.fileversion }}.zip $url

      - name: Update pages Repository
        working-directory: ./gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add repo.xml
          git add CustomClock${{ steps.set-filename.outputs.fileversion }}.zip
          git commit -m "Update CustomClock for Release ${{ steps.set-version.outputs.version }}"
          git push origin HEAD:gh-pages

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-version.outputs.version }}
          name: Version ${{ steps.set-version.outputs.version }}
          body: Custom Clock for Release
          draft: false
          prerelease: false
          files: CustomClock${{ steps.set-filename.outputs.fileversion }}.zip
